/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.emailproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harnk
 */
public class Frm_GelenMailler extends javax.swing.JFrame {

    Kullanici kullanici;
    //DefaultTableModel tbl_mailler_model;
    DefaultTableModel model;

    /**
     * Creates new form Frm_mesajGonder
     */
    public Frm_GelenMailler(Kullanici person) {
        this.kullanici = person;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_gelenMail = new javax.swing.JTable();
        btn_gelenMailler = new javax.swing.JButton();
        btn_okunduMu = new javax.swing.JButton();
        btn_okunduSil = new javax.swing.JButton();
        btn_gereksizMailler = new javax.swing.JButton();
        btn_cikis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 500));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MAİLLER", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI Semibold", 3, 24), new java.awt.Color(255, 255, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 102));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));

        jtbl_gelenMail.setBackground(new java.awt.Color(255, 255, 153));
        jtbl_gelenMail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kimden", "Konu", "Gelen Mail", "Mesaj Türü", "Okundu Olarak İşaretle"
            }
        ));
        jScrollPane1.setViewportView(jtbl_gelenMail);
        if (jtbl_gelenMail.getColumnModel().getColumnCount() > 0) {
            jtbl_gelenMail.getColumnModel().getColumn(4).setHeaderValue("Okundu Olarak İşaretle");
        }

        btn_gelenMailler.setBackground(new java.awt.Color(255, 255, 153));
        btn_gelenMailler.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_gelenMailler.setText("Mailleri Göster");
        btn_gelenMailler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gelenMaillerActionPerformed(evt);
            }
        });

        btn_okunduMu.setBackground(new java.awt.Color(255, 255, 153));
        btn_okunduMu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_okunduMu.setText("Okundu Olarak İşaretle");
        btn_okunduMu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okunduMuActionPerformed(evt);
            }
        });

        btn_okunduSil.setBackground(new java.awt.Color(255, 255, 153));
        btn_okunduSil.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_okunduSil.setText("Okunmadı Olarak İşaretle");
        btn_okunduSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okunduSilActionPerformed(evt);
            }
        });

        btn_gereksizMailler.setBackground(new java.awt.Color(255, 255, 153));
        btn_gereksizMailler.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_gereksizMailler.setText("Gereksiz Mailleri Göster");
        btn_gereksizMailler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gereksizMaillerActionPerformed(evt);
            }
        });

        btn_cikis.setBackground(new java.awt.Color(255, 255, 153));
        btn_cikis.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_cikis.setText("Çıkış");
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_okunduMu, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_gelenMailler, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_okunduSil, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_gereksizMailler, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gelenMailler)
                    .addComponent(btn_gereksizMailler, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_okunduMu)
                    .addComponent(btn_okunduSil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gelenMaillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gelenMaillerActionPerformed
        // Kullanıcının gelen maillerini veritabanından çeker ve tabloya ekler.
        ArrayList<Mailler> mailler = DB_Kullanici_Management.GetReceivedMailler(kullanici);
        model = (DefaultTableModel) jtbl_gelenMail.getModel();
        model.setRowCount(0); // tabloyu temizle
        for (Mailler mail : mailler) {
            if (kullanici.id == mail.receiverID) {
                // tabloya gelen maili ekle
                model.addRow(new Object[]{mail.emailkimden, mail.konu, mail.emailMesaj, mail.yildizliMi ? "Yıldızlı" : "Normal", mail.okunduMu ? "Okundu" : "Okunmadı"});
            }
        }
    }//GEN-LAST:event_btn_gelenMaillerActionPerformed

    private void btn_okunduMuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okunduMuActionPerformed
        // Seçili maili 'okundu' olarak işaretler.
        int selectedRow = jtbl_gelenMail.getSelectedRow();
        if (selectedRow != -1) {
            String emailKonu = jtbl_gelenMail.getValueAt(selectedRow, 1).toString();

            Connection conn = null;
            PreparedStatement pstmt = null;
            try {
                conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/db_email?user=root&password=Harun.kaya1");

                String sql = "UPDATE tbl_mesaj_gonder SET okunduMu = ? WHERE emailKonu = ?";

                pstmt = conn.prepareStatement(sql);
                pstmt.setBoolean(1, true); // burada değişiklik yaptık
                pstmt.setString(2, emailKonu);

                pstmt.executeUpdate();
                System.out.println(pstmt.getUpdateCount());
            } catch (SQLException e) {
                e.printStackTrace();
            } finally {
                try {
                    if (pstmt != null) {
                        pstmt.close();
                    }
                    if (conn != null) {
                        conn.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }

            DefaultTableModel model = (DefaultTableModel) jtbl_gelenMail.getModel();
            model.setValueAt("Okundu", selectedRow, 4);
        }

    }//GEN-LAST:event_btn_okunduMuActionPerformed

    private void btn_okunduSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okunduSilActionPerformed
        // Seçili maili 'okunmadı' olarak işaretler.
        int selectedRow = jtbl_gelenMail.getSelectedRow();
        if (selectedRow != -1) {
            String emailKonu = jtbl_gelenMail.getValueAt(selectedRow, 1).toString();

            Connection conn = null;
            PreparedStatement pstmt = null;
            try {
                conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/db_email?user=root&password=Harun.kaya1");

                String sql = "UPDATE tbl_mesaj_gonder SET okunduMu = ? WHERE emailKonu = ?";

                pstmt = conn.prepareStatement(sql);
                pstmt.setBoolean(1, false); // burada değişiklik yaptık
                pstmt.setString(2, emailKonu);

                pstmt.executeUpdate();
                System.out.println(pstmt.getUpdateCount());
            } catch (SQLException e) {
                e.printStackTrace();
            } finally {
                try {
                    // Süreç sırasında oluşabilecek herhangi bir SQL istisnasını yönetir.
                    // Bu, bağlantı hatası veya yanlış SQL sorgusu gibi çeşitli faktörlerden kaynaklanabilir.
                    if (pstmt != null) {
                        pstmt.close();
                    }
                    if (conn != null) {
                        conn.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }

            DefaultTableModel model = (DefaultTableModel) jtbl_gelenMail.getModel();
            model.setValueAt("Okunmadı", selectedRow, 4);
        }
    }//GEN-LAST:event_btn_okunduSilActionPerformed

    private void btn_gereksizMaillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gereksizMaillerActionPerformed
        // TODO add your handling code here:
        Frm_GereksizMailler gereksizMailler = new Frm_GereksizMailler(kullanici);
        gereksizMailler.setVisible(true);
    }//GEN-LAST:event_btn_gereksizMaillerActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
        // TODO add your handling code here:
        Object[] options = {"Mail Gönder", "Mail Sil","Çıkış Yap"};
    int n = JOptionPane.showOptionDialog(rootPane, "Ne yapmak istersiniz?", "Başarılı Giriş",
    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
    // Kullanıcının seçimine göre ilgili form açılır
    if(n == 0) {
        Frm_MesajOlusturGonder frm_mesajOlusturGonder = new Frm_MesajOlusturGonder(kullanici);
        frm_mesajOlusturGonder.setVisible(true);
    } else if(n == 1) {
        Frm_Silinen_Mailler frm_silinenMailler = new Frm_Silinen_Mailler(kullanici);
        frm_silinenMailler.setVisible(true);
    } else if(n == 2) {
        this.dispose();
    }
    }//GEN-LAST:event_btn_cikisActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_gelenMailler;
    private javax.swing.JButton btn_gereksizMailler;
    private javax.swing.JButton btn_okunduMu;
    private javax.swing.JButton btn_okunduSil;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbl_gelenMail;
    // End of variables declaration//GEN-END:variables
}
