/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.emailproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author harnk
 */
public class Frm_Silinen_Mailler extends javax.swing.JFrame {

    Kullanici kullanici;
    //DefaultTableModel tbl_mailler_model;
    DefaultTableModel model;

    /**
     * Creates new form Frm_Silinen_Mailler
     */
    public Frm_Silinen_Mailler(Kullanici person) {
        this.kullanici = person;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_mailler = new javax.swing.JTable();
        btn_gelenMailler = new javax.swing.JButton();
        btn_gidenMailler = new javax.swing.JButton();
        btn_mailSil = new javax.swing.JButton();
        btn_cikis = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbl_silinenMailler = new javax.swing.JTable();
        btn_silinenMailler = new javax.swing.JButton();
        btn_cikis1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));

        jPanel4.setBackground(new java.awt.Color(153, 204, 255));

        jtbl_mailler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mail Adresi", "Konu", "Mail", "Mail Türü ", "Okundu Mu"
            }
        ));
        jScrollPane1.setViewportView(jtbl_mailler);

        btn_gelenMailler.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_gelenMailler.setText("Gelen Mailleri Göster");
        btn_gelenMailler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gelenMaillerActionPerformed(evt);
            }
        });

        btn_gidenMailler.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_gidenMailler.setText("Giden Mailleri Göster");
        btn_gidenMailler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gidenMaillerActionPerformed(evt);
            }
        });

        btn_mailSil.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_mailSil.setText("Mail Sil");
        btn_mailSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mailSilActionPerformed(evt);
            }
        });

        btn_cikis.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_cikis.setText("Çıkış");
        btn_cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btn_gelenMailler, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_gidenMailler, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btn_mailSil, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btn_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gelenMailler, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gidenMailler, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_mailSil, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cikis, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mailler", jPanel2);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jtbl_silinenMailler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mail Adresi", "Konu", "Mail", "Mail Türü", "Okundu Mu"
            }
        ));
        jScrollPane2.setViewportView(jtbl_silinenMailler);

        btn_silinenMailler.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_silinenMailler.setText("Silinen Mailleri Göster");
        btn_silinenMailler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_silinenMaillerActionPerformed(evt);
            }
        });

        btn_cikis1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btn_cikis1.setText("Çıkış");
        btn_cikis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cikis1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_silinenMailler, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(btn_cikis1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_silinenMailler, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cikis1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Silinen Mailler", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_gelenMaillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gelenMaillerActionPerformed
      

        ArrayList<Mailler> mailler = DB_Kullanici_Management.GetAlınanMailler(kullanici);
        model = (DefaultTableModel) jtbl_mailler.getModel();
        model.setRowCount(0); // tabloyu temizle
        for (Mailler mail : mailler) {
            if (kullanici.id == mail.receiverID) {
                // tabloya gelen maili ekle
                model.addRow(new Object[]{mail.kime, mail.konu, mail.emailMesaj, mail.yildizliMi ? "Yıldızlı" : "Normal", (mail.okunduMu != null && mail.okunduMu) ? "Okundu" : "Okunmadı"});
            }
        }


    }//GEN-LAST:event_btn_gelenMaillerActionPerformed


    private void btn_gidenMaillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gidenMaillerActionPerformed
        // TODO add your handling code here:
        ArrayList<Mailler> mailler = DB_Kullanici_Management.GetGönderilenMailler(kullanici);
        model = (DefaultTableModel) jtbl_mailler.getModel();
        model.setRowCount(0); // tabloyu temizle
        for (Mailler mail : mailler) {
            if (kullanici.id == mail.senderID) {
                // tabloya gelen maili ekle
                model.addRow(new Object[]{mail.emailkimden, mail.konu, mail.emailMesaj, mail.yildizliMi ? "Yıldızlı" : "Normal", (mail.okunduMu != null && mail.okunduMu) ? "Okundu" : "Okunmadı"});
            }
        }
    }//GEN-LAST:event_btn_gidenMaillerActionPerformed

    private void btn_mailSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mailSilActionPerformed
        // TODO add your handling code here:
        int selectedRow = jtbl_mailler.getSelectedRow();
        if (selectedRow != -1) {
            String emailKime = model.getValueAt(selectedRow, 0).toString();
            String emailKonu = model.getValueAt(selectedRow, 1).toString();
            String emailMesaji = model.getValueAt(selectedRow, 2).toString();

            Connection conn = null;
            PreparedStatement pstmt = null;
            try {
                conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/db_email?user=root&password=Harun.kaya1");

                // Önce silinen e-postayı tbl_silinen_mailler içine ekleyin
                String insertSql = "INSERT INTO tbl_silinen_mailler(senderID, receiverID, emailKime, emailKonu, emailMesaji, yildizliMesaj, okunduMu) SELECT senderID, receiverID, emailKime, emailKonu, emailMesaji, yildizliMesaj, okunduMu FROM tbl_mesaj_gonder WHERE emailKime = ? AND emailKonu = ? AND emailMesaji = ?";
                pstmt = conn.prepareStatement(insertSql);
                pstmt.setString(1, emailKime);
                pstmt.setString(2, emailKonu);
                pstmt.setString(3, emailMesaji);
                pstmt.executeUpdate();

                // Sonra e-postayı tbl_mesaj_gonder'dan silin
                String deleteSql = "DELETE FROM tbl_mesaj_gonder WHERE emailKime = ? AND emailKonu = ? AND emailMesaji = ?";
                pstmt = conn.prepareStatement(deleteSql);
                pstmt.setString(1, emailKime);
                pstmt.setString(2, emailKonu);
                pstmt.setString(3, emailMesaji);
                pstmt.executeUpdate();
            } catch (SQLException e) {
                e.printStackTrace();
            } finally {
                try {
                    if (pstmt != null) {
                        pstmt.close();
                    }
                    if (conn != null) {
                        conn.close();
                    }
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }

            model.removeRow(selectedRow);
        }
        
    }//GEN-LAST:event_btn_mailSilActionPerformed

    private void btn_silinenMaillerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_silinenMaillerActionPerformed
      
         try {
        String url = "jdbc:mysql://127.0.0.1:3306/db_email?user=root&password=Harun.kaya1";
        
        Connection conn = DriverManager.getConnection(url);
        Statement stmt = conn.createStatement();
        String query = "SELECT emailKime, emailKonu, emailMesaji, yildizliMesaj, okunduMu FROM tbl_silinen_mailler";
        ResultSet rs = stmt.executeQuery(query);
        
        DefaultTableModel model = (DefaultTableModel) jtbl_silinenMailler.getModel();
        model.setRowCount(0);
        
        while (rs.next()) {
            Object[] row = new Object[5];
            row[0] = rs.getString("emailKime");
            row[1] = rs.getString("emailKonu");
            row[2] = rs.getString("emailMesaji");
            // yildizliMesaj ve okunduMu değerlerini dönüştürüyoruz.
            if (rs.getBoolean("yildizliMesaj")) {
                row[3] = "Yıldızlı Mail";
            } else {
                row[3] = "Normal Mail";
            }
            
            if (rs.getBoolean("okunduMu")) {
                row[4] = "Okundu";
            } else {
                row[4] = "Okunmadı";
            }
            
            model.addRow(row);
        }
        
        rs.close();
        stmt.close();
        conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_btn_silinenMaillerActionPerformed

    private void btn_cikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikisActionPerformed
        // TODO add your handling code here:
         Object[] options = {"Mail Gönder", "Mail Oku","Çıkış Yap"};
    int n = JOptionPane.showOptionDialog(rootPane, "Ne yapmak istersiniz?", "Başarılı Giriş",
    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
    // Kullanıcının seçimine göre ilgili form açılır
    if(n == 0) {
        Frm_MesajOlusturGonder frm_mesajOlusturGonder = new Frm_MesajOlusturGonder(kullanici);
        frm_mesajOlusturGonder.setVisible(true);
    } else if(n == 1) {
        Frm_GelenMailler frm_mesajGonder = new Frm_GelenMailler(kullanici);
        frm_mesajGonder.setVisible(true);
    } else if(n == 2) {
        this.dispose();
    }
    }//GEN-LAST:event_btn_cikisActionPerformed

    private void btn_cikis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cikis1ActionPerformed
        // TODO add your handling code here: 
        Object[] options = {"Mail Gönder", "Mail Oku","Çıkış Yap"};
    int n = JOptionPane.showOptionDialog(rootPane, "Ne yapmak istersiniz?", "Başarılı Giriş",
    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
    // Kullanıcının seçimine göre ilgili form açılır
    if(n == 0) {
        Frm_MesajOlusturGonder frm_mesajOlusturGonder = new Frm_MesajOlusturGonder(kullanici);
        frm_mesajOlusturGonder.setVisible(true);
    } else if(n == 1) {
        Frm_GelenMailler frm_mesajGonder = new Frm_GelenMailler(kullanici);
        frm_mesajGonder.setVisible(true);
    } else if(n == 2) {
        this.dispose();
    }
    }//GEN-LAST:event_btn_cikis1ActionPerformed
    public void showDeletedMails() {
        // Veritabanına bağlanmak için bilgiler
        String url = "jdbc:mysql://127.0.0.1:3306/db_email?user=root&password=Harun.kaya1";

        // JTable için bir tablo modeli oluşturun
        DefaultTableModel model = (DefaultTableModel) jtbl_silinenMailler.getModel();
        model.setRowCount(0); // Tabloyu temizle

        // Veritabanına bağlan ve silinmiş mailleri al
        try ( Connection conn = DriverManager.getConnection(url)) {
            String sql = "SELECT * FROM tbl_silinen_mailler";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sql);

            // Sonuçları tablo modeline ekle
            while (rs.next()) {
                Object[] row = new Object[model.getColumnCount()];
                for (int i = 0; i < model.getColumnCount(); i++) {
                    row[i] = rs.getObject(i + 1);
                }
                model.addRow(row);
            }

            // Yeni verileri tabloda göster
            jtbl_silinenMailler.setModel(model);

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cikis;
    private javax.swing.JButton btn_cikis1;
    private javax.swing.JButton btn_gelenMailler;
    private javax.swing.JButton btn_gidenMailler;
    private javax.swing.JButton btn_mailSil;
    private javax.swing.JButton btn_silinenMailler;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtbl_mailler;
    private javax.swing.JTable jtbl_silinenMailler;
    // End of variables declaration//GEN-END:variables
}
