 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.emailproject;

import java.awt.Image;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author harnk
 */
public class Frm_Login extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Login
     */
    public Frm_Login() {
        initComponents();
        addImageToPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_login = new javax.swing.JPanel();
        txt_email = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        psw_field = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        pnl_resim = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        setMinimumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(500, 600));

        pnl_login.setBackground(new java.awt.Color(0, 204, 204));
        pnl_login.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 255)));
        pnl_login.setMinimumSize(new java.awt.Dimension(500, 600));
        pnl_login.setPreferredSize(new java.awt.Dimension(500, 600));
        pnl_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_email.setBackground(new java.awt.Color(255, 204, 153));
        pnl_login.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 73, 174, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel1.setText("Email");
        pnl_login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 73, 59, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Şifre");
        pnl_login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 164, -1, -1));

        psw_field.setBackground(new java.awt.Color(255, 204, 153));
        pnl_login.add(psw_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 164, 174, 31));

        btn_login.setBackground(new java.awt.Color(255, 204, 153));
        btn_login.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_login.setText("Giriş Yap");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        pnl_login.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 139, 85));

        btn_register.setBackground(new java.awt.Color(255, 204, 153));
        btn_register.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        btn_register.setText("Kayıt Ol");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });
        pnl_login.add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 139, 85));

        pnl_resim.setLayout(null);
        pnl_login.add(pnl_resim, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 220, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_login, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String email = txt_email.getText();
    String password = psw_field.getText();
    
    try {
        // Kullanıcının giriş yapma denemesi
        Kullanici person = DB_Kullanici_Management.Login(email, password);

        if(person != null) {// Giriş başarılıysa
            // Kullanıcıya ne yapmak istediğini soran bir seçenek kutusu oluşturulur
    Object[] options = {"Mailleri Oku", "Mail Gönder", "Mail Sil"};
    int n = JOptionPane.showOptionDialog(rootPane, "Ne yapmak istersiniz?", "Başarılı Giriş",
    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
    // Kullanıcının seçimine göre ilgili form açılır
    if(n == 0) {
        Frm_GelenMailler frm_mesajGonder = new Frm_GelenMailler(person);
        frm_mesajGonder.setVisible(true);
    } else if(n == 1) {
        Frm_MesajOlusturGonder frm_mesajOlusturGonder = new Frm_MesajOlusturGonder(person);
        frm_mesajOlusturGonder.setVisible(true);
    } else if(n == 2) {
        Frm_Silinen_Mailler frm_silinenMailler = new Frm_Silinen_Mailler(person);
        frm_silinenMailler.setVisible(true);
    }
} else {
    JOptionPane.showMessageDialog(rootPane, "Başarısız giriş");
}
} catch (Exception ex) {
    JOptionPane.showMessageDialog(rootPane, "Bir hata oluştu: " + ex.getMessage());
}

    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    Frm_Register frm_register = new Frm_Register(this); 
    frm_register.setVisible(true);
    }//GEN-LAST:event_btn_registerActionPerformed
private void addImageToPanel() {
    String imagePath = "C:\\Users\\harnk\\OneDrive\\Resimler\\Saved Pictures\\emailresim.jpg"; 
    ImageIcon imageIcon = new ImageIcon(new ImageIcon(imagePath).getImage().getScaledInstance(pnl_resim.getWidth(), pnl_resim.getHeight(), Image.SCALE_DEFAULT));
    JLabel imgLabel = new JLabel(imageIcon);

    imgLabel.setBounds(0, 0, pnl_resim.getWidth(), pnl_resim.getHeight()); 
    pnl_resim.add(imgLabel);
    pnl_resim.revalidate();
    pnl_resim.repaint();
}
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JPanel pnl_resim;
    private javax.swing.JPasswordField psw_field;
    private javax.swing.JTextField txt_email;
    // End of variables declaration//GEN-END:variables
}
